"""update user model and add folder table

Revision ID: aa168c2ada25
Revises: 5c9afde1ddc5
Create Date: 2025-01-24 09:12:28.591237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa168c2ada25'
down_revision: Union[str, None] = '5c9afde1ddc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profession', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('theme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    op.drop_column('users', 'language')
    op.drop_column('users', 'profession')
    # ### end Alembic commands ###
